import { CzmParticleEmitterJsonType, Player } from "xbsj-xe2/dist-node/xe2-base-objects";
import { JsonValue, Listener, PartialWithUndefinedReactivePropsToNativeProps, ReactivePropsToNativePropsAndChanged } from "xbsj-xe2/dist-node/xe2-base-utils";
import { SceneObjectKey } from "xbsj-xe2/dist-node/xe2-utils";
import { ESObjectWithLocation } from "../../base/objs";
export declare class ESParticleSystemPrimitive extends ESObjectWithLocation {
    static readonly type: string;
    get typeName(): string;
    get defaultProps(): {
        show: boolean;
        collision: boolean;
        allowPicking: boolean;
        flyToParam: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<import("../..").ESFlyToParam | undefined>;
        flyInParam: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<import("../..").ESFlyInParam | undefined>;
        execOnceFuncStr: string | undefined;
        updateFuncStr: string | undefined;
        toDestroyFuncStr: string | undefined;
        name: string;
        ref: string | undefined;
        devTags: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<string[] | undefined>;
        extras: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<JsonValue>;
        position: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number]>;
        rotation: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number]>;
        scale: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number]>;
        emitter: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<CzmParticleEmitterJsonType | undefined>;
        bursts: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[time?: number | undefined, minimum?: number | undefined, maximum?: number | undefined][] | undefined>;
        translation: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number] | undefined>;
        positionEditing: boolean | undefined;
        image: string | undefined;
        imageSize: [number, number] | undefined;
        minimumImageSize: [number, number] | undefined;
        maximumImageSize: [number, number] | undefined;
        updateCallback: string | undefined;
        emissionRate: number | undefined;
        loop: boolean | undefined;
        particleScale: number | undefined;
        startScale: number | undefined;
        endScale: number | undefined;
        color: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number, number] | undefined>;
        startColor: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number, number] | undefined>;
        endColor: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number, number] | undefined>;
        sizeInMeters: boolean | undefined;
        speed: number | undefined;
        minimumSpeed: number | undefined;
        maximumSpeed: number | undefined;
        lifetime: number | undefined;
        particleLife: number | undefined;
        minimumParticleLife: number | undefined;
        maximumParticleLife: number | undefined;
        mass: number | undefined;
        minimumMass: number | undefined;
        maximumMass: number | undefined;
        playingLoop: boolean | undefined;
        currentTime: number | undefined;
        duration: number | undefined;
        playingSpeed: number | undefined;
        playing: boolean | undefined;
    };
    get json(): JsonType;
    set json(value: JsonType);
    private _player;
    get player(): Player;
    get ratio(): number;
    set ratio(value: number);
    get ratioChanged(): Listener<[number, number]>;
    constructor(id?: SceneObjectKey);
    static defaults: {
        playingLoop: boolean;
        currentTime: number;
        playerCurrentTime: number;
        duration: number;
        playingSpeed: number;
        playing: boolean;
        ratio: number;
        particleLife: number;
        endScale: number;
        imageSize: [number, number];
        image: string;
        emitter: CzmParticleEmitterJsonType;
        show: boolean;
        collision: boolean;
        allowPicking: boolean;
        flyToParam: import("../..").ESFlyToParam;
        flyInParam: import("../..").ESFlyInParam;
        viewerTagsEnums: [string, string][];
    };
    getProperties(language?: string): import("xbsj-xe2/dist-node/xe2-base-objects").Property[];
}
export declare namespace ESParticleSystemPrimitive {
    const createDefaultProps: () => {
        show: boolean;
        collision: boolean;
        allowPicking: boolean;
        flyToParam: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<import("../..").ESFlyToParam | undefined>;
        flyInParam: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<import("../..").ESFlyInParam | undefined>;
        execOnceFuncStr: string | undefined;
        updateFuncStr: string | undefined;
        toDestroyFuncStr: string | undefined;
        name: string;
        ref: string | undefined;
        devTags: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<string[] | undefined>;
        extras: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<JsonValue>;
        position: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number]>;
        rotation: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number]>;
        scale: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number]>;
        emitter: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<CzmParticleEmitterJsonType | undefined>;
        bursts: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[time?: number | undefined, minimum?: number | undefined, maximum?: number | undefined][] | undefined>;
        translation: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number] | undefined>;
        positionEditing: boolean | undefined;
        image: string | undefined;
        imageSize: [number, number] | undefined;
        minimumImageSize: [number, number] | undefined;
        maximumImageSize: [number, number] | undefined;
        updateCallback: string | undefined;
        emissionRate: number | undefined;
        loop: boolean | undefined;
        particleScale: number | undefined;
        startScale: number | undefined;
        endScale: number | undefined;
        color: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number, number] | undefined>;
        startColor: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number, number] | undefined>;
        endColor: import("xbsj-xe2/dist-node/xe2-base-utils").ReactiveVariable<[number, number, number, number] | undefined>;
        sizeInMeters: boolean | undefined;
        speed: number | undefined;
        minimumSpeed: number | undefined;
        maximumSpeed: number | undefined;
        lifetime: number | undefined;
        particleLife: number | undefined;
        minimumParticleLife: number | undefined;
        maximumParticleLife: number | undefined;
        mass: number | undefined;
        minimumMass: number | undefined;
        maximumMass: number | undefined;
        playingLoop: boolean | undefined;
        currentTime: number | undefined;
        duration: number | undefined;
        playingSpeed: number | undefined;
        playing: boolean | undefined;
    };
}
export interface ESParticleSystemPrimitive extends ReactivePropsToNativePropsAndChanged<ReturnType<typeof ESParticleSystemPrimitive.createDefaultProps>> {
}
declare type JsonType = PartialWithUndefinedReactivePropsToNativeProps<ReturnType<typeof ESParticleSystemPrimitive.createDefaultProps> & {
    type: string;
}>;
export {};
